In [1]:
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Load training and test data
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")


In [2]:
# Define k for k-NN
k = 5


In [3]:
# Calculate Euclidean distance
def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2) ** 2))


In [4]:
# Get k-nearest neighbors
def get_neighbors(training_data, test_row, k):
    distances = []
    for _, train_row in training_data.iterrows():
        dist = euclidean_distance(test_row[:-1], train_row[:-1])  # Ignore label column for distance calculation
        distances.append((train_row[-1], dist))  # (label, distance)
    distances.sort(key=lambda x: x[1])
    neighbors = [distances[i][0] for i in range(k)]  # Get k closest labels
    return neighbors


In [5]:
# Make prediction based on majority vote
def predict(training_data, test_row, k):
    neighbors = get_neighbors(training_data, test_row, k)
    return Counter(neighbors).most_common(1)[0][0]  # Most common label among neighbors


In [6]:
# Evaluate model
def evaluate_knn(training_data, test_data, k):
    y_true = test_data.iloc[:, -1]
    y_pred = test_data.apply(lambda row: predict(training_data, row, k), axis=1)
    
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='macro')
    recall = recall_score(y_true, y_pred, average='macro')
    conf_matrix = confusion_matrix(y_true, y_pred)
    
    print("Confusion Matrix:\n", conf_matrix)
    print(f"Accuracy: {accuracy:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    return accuracy, precision, recall


In [7]:
# Run evaluation
accuracy, precision, recall = evaluate_knn(train_data, test_data, k)


C:\Users\ASUS\AppData\Local\Temp\ipykernel_26524\3142045766.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  distances.append((train_row[-1], dist))  # (label, distance)


Confusion Matrix:
 [[12  0  0]
 [ 0 13  0]
 [ 0  1 12]]
Accuracy: 0.97
Precision: 0.98
Recall: 0.97
